INSERT INTO suggestions(query,type) VALUES('jefferson','1');
INSERT INTO suggestions(query,type) VALUES('chicago','1');
INSERT INTO suggestions(query,type) VALUES('jennifer aniston','2');
INSERT INTO suggestions(query,type) VALUES('keith urban','2');
INSERT INTO suggestions(query,type) VALUES('barry bonds babe ruth record','3');
INSERT INTO suggestions(query,type) VALUES('bush','1');
INSERT INTO suggestions(query,type) VALUES('kobe bryant','2');
INSERT INTO suggestions(query,type) VALUES('paris hilton','2');
INSERT INTO suggestions(query,type) VALUES('jordan','1');
INSERT INTO suggestions(query,type) VALUES('william jefferson clinton','3');
INSERT INTO suggestions(query,type) VALUES('vince vaughn owen wilson movie','3');
INSERT INTO suggestions(query,type) VALUES('brad pitt snatch','3');
INSERT INTO suggestions(query,type) VALUES('celine dion','1');
INSERT INTO suggestions(query,type) VALUES('paris','1');
INSERT INTO suggestions(query,type) VALUES('mickey rourke','2');
INSERT INTO suggestions(query,type) VALUES('brad pitt','2');
INSERT INTO suggestions(query,type) VALUES('michael jackson','1');
INSERT INTO suggestions(query,type) VALUES('john f kennedy','3');
INSERT INTO suggestions(query,type) VALUES('tom brady','3');
INSERT INTO suggestions(query,type) VALUES('jonas brothers','2');
INSERT INTO suggestions(query,type) VALUES('miley cyrus','2');
INSERT INTO suggestions(query,type) VALUES('barack obama','2');
INSERT INTO suggestions(query,type) VALUES('tiger woods','2');
INSERT INTO suggestions(query,type) VALUES('johnny depp','2');
INSERT INTO suggestions(query,type) VALUES('bill gates','2');
INSERT INTO suggestions(query,type) VALUES('pamela anderson','2');
INSERT INTO suggestions(query,type) VALUES('dicaprio','1');
INSERT INTO suggestions(query,type) VALUES('kate hudson','2');
INSERT INTO suggestions(query,type) VALUES('david letterman','2');
INSERT INTO suggestions(query,type) VALUES('samuel adams boston massachusetts','3');
INSERT INTO suggestions(query,type) VALUES('britney spears','2');
INSERT INTO suggestions(query,type) VALUES('roosevelt','1');
INSERT INTO suggestions(query,type) VALUES('clint eastwood','2');
INSERT INTO suggestions(query,type) VALUES('oprah winfrey','2');
INSERT INTO suggestions(query,type) VALUES('john mccain','2');
INSERT INTO suggestions(query,type) VALUES('madonna','2');
INSERT INTO suggestions(query,type) VALUES('rodert de niro','2');
INSERT INTO suggestions(query,type) VALUES('al gore','2');
INSERT INTO suggestions(query,type) VALUES('martin luther king','3');
INSERT INTO suggestions(query,type) VALUES('alex rodriguez','2');
INSERT INTO suggestions(query,type) VALUES('harrison ford','2');
INSERT INTO suggestions(query,type) VALUES('frank sinatra','2');
INSERT INTO suggestions(query,type) VALUES('miley cyrus','2');
INSERT INTO suggestions(query,type) VALUES('david bowie','2');
INSERT INTO suggestions(query,type) VALUES('ronald reagan','2');
INSERT INTO suggestions(query,type) VALUES('mariah carey','2');
INSERT INTO suggestions(query,type) VALUES('winona ryder','2');
INSERT INTO suggestions(query,type) VALUES('elvis presley','2');
INSERT INTO suggestions(query,type) VALUES('michael phelps','2');
INSERT INTO suggestions(query,type) VALUES('mel gibson','2');



